# --- Site settings --- #
title: Upsilon Medical
description: The Public Home Page for Upsilon Medical Corporation. 

# --- Local Development Options --- #
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# --- Contact Info --- #
# phone: (xxx) xxx - xxxx
email: upsilonmedicalcorporation@gmail.com
twitter_username:
github_username:
# facebook_username: 
# instagram_username:
# youtube_username:
# ADD OTHER SOCIAL MEDIA LINKS AS NEEDED BELOW

# Build settings
markdown: kramdown
